/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : egkreader
 #	author : AB
 #	26.07.17
 #
 # --------------------------------------------------------------------------------*/

#pragma once

enum{
	eCMD_egkreader = 1
};


// ----------------------------------- egkreader ----------------------------------
enum eCommands
{
    eCmdOpenCT = 1,
    eCmdCloseCT,
    eCmdReadCard,
    eCmdEjectCard,
    eCmdCardState,
    eCmdExit,
    eCmdSetLib,
    eCmdEraseBin
};


// --- egkreader
void egkreader( PA_PluginParameters params );
long DoCC3access(long cmd, long *pDataLen, unsigned char *pData);

